before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - linux
    goarch:
      - amd64
    binary: 'bootstrap'
    id: aws-security-hub-collector
    dir: aws-security-hub-collector
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_aws-security-hub-collector_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    id: aws-security-hub-collector
    builds:
      - aws-security-hub-collector
release:
changelog:
  skip: true
