name: Tests

on: [pull_request]

jobs:
  test:
    env:
      GO111MODULE: on
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Before install
      run: |
        go get golang.org/x/tools/cmd/cover
        go get github.com/mattn/goveralls
    - name: Test
      run: |
        cd collector
        go test -v -race -covermode=atomic
